id: P7897FB7B
initial_creation_type: input
source_metadata:
  title: Saddharmapuṇḍarīka
  language: en
  volumes:
    0c49b573399f467b9e9222d37776301b:
      title: 1. Nidāna
      base_file: 1. Nidāna.txt
      work_id: W6C4249CC
    b221cb64aae340a58ec6eea1388949bd:
      title: 10. Dharmabhāṇaka
      base_file: 10. Dharmabhāṇaka.txt
      work_id: W8A8E979E
    84b9977e500845028f833c642e4f8605:
      title: 11. Stūpasaṃdarśana
      base_file: 11. Stūpasaṃdarśana.txt
      work_id: W04085048
    10cf21c7a3d74f158563cd76e306095a:
      title: 12. Utsāha
      base_file: 12. Utsāha.txt
      work_id: WB4222873
    981269a22e6a43afa79d12dd1d77f3b7:
      title: 13. Sukhavihāra
      base_file: 13. Sukhavihāra.txt
      work_id: W5D31A66D
    b09a04b86c6d45d6a73e803f6f73f336:
      title: 14. Bodhisattvapṛthivīvirasamudgama
      base_file: 14. Bodhisattvapṛthivīvirasamudgama.txt
      work_id: WB5CB3E32
    db727a7786d84ebf887be9107af063f9:
      title: 15. Tathāgatāyuṣpramāṇa
      base_file: 15. Tathāgatāyuṣpramāṇa.txt
      work_id: WA19A7634
    e7c7da8555d94a2d99c3fd0fa8408c11:
      title: 16. Puṇyaparyāya
      base_file: 16. Puṇyaparyāya.txt
      work_id: WDBB29658
    3c1699d5d1fa457a903a58f3d2c96d76:
      title: 17. Anumodanāpuṇyanirdeśa
      base_file: 17. Anumodanāpuṇyanirdeśa.txt
      work_id: W6E4A6474
    193b949d5057443fbd31276369fe0030:
      title: 18. Dharmabhāṇakānuśaṃsā
      base_file: 18. Dharmabhāṇakānuśaṃsā.txt
      work_id: W0D09AF32
    369a146d66c24c2996e7b5b28bc91b77:
      title: 19. Sadāparibhūta
      base_file: 19. Sadāparibhūta.txt
      work_id: W828364D2
    0c9145a61ebb4dfabb8d0c469fbdbb6c:
      title: 2. Upāyakauśalya
      base_file: 2. Upāyakauśalya.txt
      work_id: W995337F5
    8ae37db9d4ad45699dbcf0a2a06b0152:
      title: 20. Tathāgataddharyabhisaṃskāra
      base_file: 20. Tathāgataddharyabhisaṃskāra.txt
      work_id: W7DD85331
    a2e7ed9de01243818437c15d2ef5f5f3:
      title: 21. Dhāraṇī
      base_file: 21. Dhāraṇī.txt
      work_id: W5DA4015A
    37b02234949e4b3eab30e81702505f6a:
      title: 22. Bhaiṣajyarājapūrvayoga
      base_file: 22. Bhaiṣajyarājapūrvayoga.txt
      work_id: W84A14FFD
    882dcb258f944af6bf18e82974a67313:
      title: 23. Gadgadasvara
      base_file: 23. Gadgadasvara.txt
      work_id: WE01FCCCC
    1028202dd5eb49e7b75fe3a3aa7a86e6:
      title: 24. Samantamukha
      base_file: 24. Samantamukha.txt
      work_id: W30D4093A
    ae165d2646d04cfaa6831e60c46f08ac:
      title: 25. Śubhavyūharājapūrvayoga
      base_file: 25. Śubhavyūharājapūrvayoga.txt
      work_id: W24F94ED9
    3d6f5992b19e4379bc75a04b0a618991:
      title: 26. Samantabhadrotsāhana
      base_file: 26. Samantabhadrotsāhana.txt
      work_id: W93D43D72
    80780aa5b0614e1eac5091dff44423ae:
      title: 27. Anuparīndanā
      base_file: 27. Anuparīndanā.txt
      work_id: WDB8458BD
    84ea5019f7db4df7ac81a22949b8d8e2:
      title: 3. Aupamya
      base_file: 3. Aupamya.txt
      work_id: W12048C7A
    207b2138330948d9b560e1243fc2c93f:
      title: 4. Adhimukti
      base_file: 4. Adhimukti.txt
      work_id: W4C9BBDD1
    3795e5152f71483c932d61b38d383296:
      title: 5. Oṣadhī
      base_file: 5. Oṣadhī.txt
      work_id: W6FDA9DBD
    95732bbba2cb4f78a09ee926a1e1f88d:
      title: 6. Vyākaraṇa
      base_file: 6. Vyākaraṇa.txt
      work_id: W892B9800
    8d05022dd36949f89f1049c82553fd0d:
      title: 7. Pūrvayoga
      base_file: 7. Pūrvayoga.txt
      work_id: W0687BA0B
    a3003dc53c4b4d558d50fb4e7478d2d1:
      title: 8. Pañcabhikṣuśatavyākaraṇa
      base_file: 8. Pañcabhikṣuśatavyākaraṇa.txt
      work_id: W79AE42ED
    26533629f7e64f83ac835d3c4c3bc29c:
      title: 9. Ānandādivyākaraṇa
      base_file: 9. Ānandādivyākaraṇa.txt
      work_id: W88C99A07
  chapter_to_tile: {}
created_at: '2022-03-01T21:49:39.140278'
last_modified_at: '2022-03-01T21:49:39.140287'
